/* =========================================================
   LUMÉ — Product & Content Data
   Single source of truth for products, categories & reviews.
   ========================================================= */

const CATEGORIES = [
  { id: "cleanser",    name: "Cleansers",     icon: "bottle",  blurb: "Melt away the day" },
  { id: "serum",       name: "Serums",        icon: "dropper", blurb: "Concentrated care" },
  { id: "moisturizer", name: "Moisturizers",  icon: "jar",     blurb: "Lock in the glow" },
  { id: "mask",        name: "Masks",         icon: "mask",    blurb: "A ritual, weekly" },
  { id: "sunscreen",   name: "Sun Care",      icon: "tube",    blurb: "Protect the glow" },
  { id: "body",        name: "Body Care",     icon: "bottle",  blurb: "Top to toe softness" },
  { id: "set",         name: "Gift Sets",     icon: "gift",    blurb: "Curated bundles" },
];

const PRODUCTS = [
  {
    id: "p01", name: "Dewdrop Gel Cleanser", category: "cleanser",
    price: 28, oldPrice: 34, rating: 4.8, reviews: 214,
    skinType: ["All skin types", "Oily", "Combination"],
    tags: ["bestseller"],
    palette: ["#F7D9DE", "#FBEAEC"],
    description: "A weightless, foaming gel that lifts away makeup and impurities without stripping your skin's natural moisture barrier. Infused with cucumber water and a whisper of rose for a soft, dewy finish.",
    ingredients: ["Aqua", "Cucumber Extract", "Rose Water", "Glycerin", "Panthenol", "Centella Asiatica Extract"],
    howToUse: "Massage onto damp skin morning and night, then rinse with lukewarm water.",
  },
  {
    id: "p02", name: "Velvet Milk Cleanser", category: "cleanser",
    price: 26, rating: 4.6, reviews: 132,
    skinType: ["Dry", "Sensitive"],
    tags: ["new"],
    palette: ["#F3E7F8", "#FBF7F2"],
    description: "A creamy, milk-textured cleanser that dissolves the day while cushioning sensitive skin in oat and shea butter softness.",
    ingredients: ["Aqua", "Oat Extract", "Shea Butter", "Glycerin", "Chamomile Extract"],
    howToUse: "Apply to dry skin, massage, then remove with a warm cloth.",
  },
  {
    id: "p03", name: "Lumière Vitamin C Serum", category: "serum",
    price: 58, oldPrice: 68, rating: 4.9, reviews: 389,
    skinType: ["All skin types", "Dull"],
    tags: ["bestseller"],
    palette: ["#D8CCF0", "#EDE6FA"],
    description: "A brightening powerhouse of 15% stabilized Vitamin C, ferulic acid and lilac stem cells that visibly evens tone and restores radiance overnight.",
    ingredients: ["Aqua", "15% Ascorbic Acid", "Ferulic Acid", "Vitamin E", "Lilac Stem Cell Extract", "Hyaluronic Acid"],
    howToUse: "Apply 3–4 drops to clean skin each morning before moisturizer and SPF.",
  },
  {
    id: "p04", name: "Bloom Hyaluronic Serum", category: "serum",
    price: 46, rating: 4.7, reviews: 256,
    skinType: ["Dry", "Dehydrated"],
    tags: [],
    palette: ["#F7D9DE", "#EDE6FA"],
    description: "Five molecular weights of hyaluronic acid plump and quench thirsty skin, leaving a plush, bouncy finish that lasts all day.",
    ingredients: ["Aqua", "Sodium Hyaluronate", "Panthenol", "Niacinamide", "Rose Extract"],
    howToUse: "Press 2–3 drops into damp skin, morning and night.",
  },
  {
    id: "p05", name: "Orchid Renewal Night Serum", category: "serum",
    price: 64, rating: 4.8, reviews: 178,
    skinType: ["Mature", "Dry"],
    tags: ["new"],
    palette: ["#C98FA0", "#D8CCF0"],
    description: "A restorative blend of retinol alternative bakuchiol and orchid extract that works while you sleep to soften fine lines and renew texture.",
    ingredients: ["Aqua", "Bakuchiol", "Orchid Extract", "Squalane", "Peptide Complex"],
    howToUse: "Apply a pea-sized amount at night after cleansing. Follow with moisturizer.",
  },
  {
    id: "p06", name: "Silk Cloud Day Cream", category: "moisturizer",
    price: 42, rating: 4.7, reviews: 301,
    skinType: ["All skin types"],
    tags: ["bestseller"],
    palette: ["#FBF7F2", "#F7D9DE"],
    description: "A cloud-light daily moisturizer that absorbs instantly, leaving skin soft, calm and luminous under makeup or bare-faced.",
    ingredients: ["Aqua", "Squalane", "Niacinamide", "Shea Butter", "Ceramides"],
    howToUse: "Smooth over face and neck each morning as the final step of your routine.",
  },
  {
    id: "p07", name: "Midnight Repair Cream", category: "moisturizer",
    price: 52, oldPrice: 60, rating: 4.8, reviews: 190,
    skinType: ["Dry", "Mature"],
    tags: [],
    palette: ["#4A3B52", "#C98FA0"],
    description: "A rich, restorative night cream that works with skin's natural repair cycle, blending peptides and lavender oil for a calm, deep-sleep glow.",
    ingredients: ["Aqua", "Shea Butter", "Peptide Complex", "Lavender Oil", "Ceramides", "Vitamin E"],
    howToUse: "Apply generously as the last step of your evening routine.",
  },
  {
    id: "p08", name: "Lilac Clay Purifying Mask", category: "mask",
    price: 34, rating: 4.6, reviews: 145,
    skinType: ["Oily", "Combination"],
    tags: [],
    palette: ["#D8CCF0", "#C98FA0"],
    description: "French lilac clay draws out impurities and refines pores while lavender water keeps skin calm instead of tight or stripped.",
    ingredients: ["Kaolin Clay", "Lilac Clay", "Lavender Water", "Aloe Vera", "Glycerin"],
    howToUse: "Apply an even layer 2x weekly, leave 10 minutes, rinse with warm water.",
  },
  {
    id: "p09", name: "Rosewater Hydrogel Mask", category: "mask",
    price: 8, priceUnit: "/ sheet", rating: 4.9, reviews: 402,
    skinType: ["All skin types", "Dehydrated"],
    tags: ["bestseller"],
    palette: ["#F7D9DE", "#FBEAEC"],
    description: "A soothing hydrogel sheet soaked in rosewater and hyaluronic acid for an instant plump, spa-fresh glow before any occasion.",
    ingredients: ["Rosewater", "Sodium Hyaluronate", "Aloe Vera", "Panthenol"],
    howToUse: "Apply to clean skin for 15–20 minutes, then pat in remaining essence.",
  },
  {
    id: "p10", name: "Petal Soft Sleeping Mask", category: "mask",
    price: 38, rating: 4.7, reviews: 98,
    skinType: ["Dry", "Sensitive"],
    tags: ["new"],
    palette: ["#EDE6FA", "#FBF7F2"],
    description: "A weightless overnight mask that seals in moisture with rose petal extract, waking skin up dewy, soft and visibly rested.",
    ingredients: ["Aqua", "Rose Petal Extract", "Squalane", "Niacinamide", "Honey Extract"],
    howToUse: "Apply as the last step at night, 2–3 times a week, no need to rinse.",
  },
  {
    id: "p11", name: "Sheer Veil Mineral SPF 50", category: "sunscreen",
    price: 36, rating: 4.8, reviews: 267,
    skinType: ["All skin types", "Sensitive"],
    tags: ["bestseller"],
    palette: ["#FBF7F2", "#D8CCF0"],
    description: "A sheer, no-white-cast mineral sunscreen with zinc oxide that layers beautifully under makeup while defending against UVA/UVB rays.",
    ingredients: ["Zinc Oxide 18%", "Aqua", "Niacinamide", "Squalane", "Vitamin E"],
    howToUse: "Apply generously as the last step each morning; reapply every 2 hours in sun.",
  },
  {
    id: "p12", name: "Glow Tint SPF 40", category: "sunscreen",
    price: 32, rating: 4.6, reviews: 154,
    skinType: ["All skin types"],
    tags: ["new"],
    palette: ["#C98FA0", "#F7D9DE"],
    description: "A tinted, dewy-finish sunscreen that evens tone and protects in one soft-focus step — makeup and skincare in a single tube.",
    ingredients: ["Zinc Oxide", "Aqua", "Iron Oxides", "Hyaluronic Acid", "Vitamin E"],
    howToUse: "Warm between fingers and press onto skin as your final morning step.",
  },
  {
    id: "p13", name: "Whipped Rose Body Butter", category: "body",
    price: 30, rating: 4.9, reviews: 221,
    skinType: ["All skin types", "Dry"],
    tags: ["bestseller"],
    palette: ["#F7D9DE", "#C98FA0"],
    description: "A fluffy, fast-absorbing body butter whipped with shea and rose oil for silky, lightly-scented softness from shoulders to toes.",
    ingredients: ["Shea Butter", "Rose Oil", "Coconut Oil", "Vitamin E"],
    howToUse: "Massage generously into skin after showering while still slightly damp.",
  },
  {
    id: "p14", name: "Lavender Bloom Body Oil", category: "body",
    price: 34, rating: 4.7, reviews: 87,
    skinType: ["All skin types"],
    tags: [],
    palette: ["#D8CCF0", "#EDE6FA"],
    description: "A dry-touch, fast-absorbing oil blending lavender and jojoba to calm the senses and leave skin softly luminous, never greasy.",
    ingredients: ["Jojoba Oil", "Lavender Oil", "Vitamin E", "Sweet Almond Oil"],
    howToUse: "Smooth over damp skin post-shower or add a few drops to a warm bath.",
  },
  {
    id: "p15", name: "Silken Hand & Nail Cream", category: "body",
    price: 18, rating: 4.5, reviews: 63,
    skinType: ["All skin types"],
    tags: [],
    palette: ["#FBEAEC", "#FBF7F2"],
    description: "A quick-absorbing hand cream with shea and rosehip that softens without leaving residue — perfect for a bag or a bedside table.",
    ingredients: ["Shea Butter", "Rosehip Oil", "Glycerin", "Vitamin E"],
    howToUse: "Massage into hands and cuticles as needed throughout the day.",
  },
  {
    id: "p16", name: "The Glow Ritual Set", category: "set",
    price: 96, oldPrice: 120, rating: 4.9, reviews: 168,
    skinType: ["All skin types"],
    tags: ["bestseller"],
    palette: ["#A78BC9", "#F7D9DE"],
    description: "Our signature three-step ritual: Dewdrop Gel Cleanser, Lumière Vitamin C Serum and Silk Cloud Day Cream, boxed in blush keepsake packaging.",
    ingredients: ["See individual products for full ingredient lists"],
    howToUse: "Cleanse, treat with serum, then seal in moisture — morning and night.",
  },
  {
    id: "p17", name: "Little Luxuries Discovery Set", category: "set",
    price: 42, rating: 4.6, reviews: 74,
    skinType: ["All skin types"],
    tags: ["new"],
    palette: ["#EDE6FA", "#C98FA0"],
    description: "Five travel-size bestsellers in a lilac pouch — the perfect way to sample the full LUMÉ ritual or gift a first taste of glow.",
    ingredients: ["See individual products for full ingredient lists"],
    howToUse: "Follow the enclosed ritual card for order of application.",
  },
  {
    id: "p18", name: "Rose Quartz Gua Sha", category: "set",
    price: 24, rating: 4.8, reviews: 132,
    skinType: ["All skin types"],
    tags: [],
    palette: ["#F7D9DE", "#FBEAEC"],
    description: "A hand-polished rose quartz tool that de-puffs and sculpts when paired with your favourite LUMÉ serum or facial oil.",
    ingredients: ["Natural Rose Quartz"],
    howToUse: "Glide upward and outward along jaw, cheeks and brow after applying oil or serum.",
  },
];

const REVIEWS = [
  { name: "Amara S.", rating: 5, text: "My skin has never looked this dewy. The Vitamin C serum is a religion at this point — I notice the difference within a day.", product: "Lumière Vitamin C Serum" },
  { name: "Priya K.", rating: 5, text: "The packaging alone made me want to buy everything, but the Silk Cloud Day Cream is what made me stay. Lightweight and glowing all day.", product: "Silk Cloud Day Cream" },
  { name: "Fatima R.", rating: 4, text: "Gentle, calming, and it actually smells like a spa. The gel cleanser has become the easiest step of my whole routine.", product: "Dewdrop Gel Cleanser" },
  { name: "Naomi L.", rating: 5, text: "I gifted the Glow Ritual Set to my sister and she has already reordered twice. Beautifully boxed and the products deliver.", product: "The Glow Ritual Set" },
  { name: "Zara H.", rating: 5, text: "The body butter absorbs so fast and the scent is soft, never overpowering. My new after-shower ritual, every single day.", product: "Whipped Rose Body Butter" },
  { name: "Mei T.", rating: 4, text: "Finally a sunscreen with zero white cast on my skin tone. Wears beautifully under makeup and doesn't pill at all.", product: "Sheer Veil Mineral SPF 50" },
];
